version: "3"
services:
  proxy:
    build:
      context: ..
      dockerfile: .build/proxy/Dockerfile
    ports:
      - "${PROXY_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - service


  backend:
    build:
      context: ..
      dockerfile: .build/app/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - service


  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-user}
      POSTGRES_DB: ${DB_NAME:-user}
    ports:
      - '5432:5432'
    volumes:
      - storage:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}" ]
      interval: 5s
      timeout: 25s
      retries: 10
    networks:
      - service

volumes:
  storage:
    driver: local

networks:
  service:
    driver: bridge